const path = require("path")

module.exports = ({
  basePath = "/",
  imagePath = "og-image",
  contentPath = "blog",
  ogWidth = 1200,
  ogHeight = 630,
  ogBackgroundColor = "rgb(255,255,255)",
  ogBackgroundImage = path.join(__dirname, "..", "assets", "background.png"),
  // ogBaseFontSize is the original size of the BMFont. Its better to use a big one and scale down.
  ogBaseFontSize = 288,
  ogFontSize = 70,
  ogVBandColor = "rgb(200,200,200)",
  ogVBandWidth = 0,
  ogHBandColor = "rgb(200,200,200)",
  ogHBandWidth = 0,
  ogTextColor = "rgb(0,71,124)",
  ogTextOpacity = 1.0,
  titleField = "seoTitle",
}) => ({
  basePath,
  imagePath,
  ogHeight,
  ogWidth,
  contentPath,
  ogBackgroundColor,
  ogBaseFontSize,
  ogFontSize,
  ogBackgroundImage,
  ogVBandColor,
  ogVBandWidth,
  ogHBandColor,
  ogHBandWidth,
  ogTextColor,
  ogTextOpacity,
  titleField,
})
